### ISSUE TITLE
Research and Implement an alternative to Doxygen

### ISSUE THREAD

**Issue by Kazzira** [Capstone-BuilderTREND-Vidportal/BuilderTREND-Video-Portal#12]
Doxygen will not work for VB.  Research something else and implement it.

Also, look for extensions for Doxygen for VB

**Comment by dswright1990** [comment]
Found http://www.helixoft.com/vsdocman/overview.html which might work for us. There is a free trial that we could use but I didn't see how long the trial lasts

**Comment by DanPatten** [comment]
This is completed
