### ISSUE TITLE
Handle Vimeo Down Issue

### ISSUE THREAD

**Issue by ccpurcell** [Capstone-BuilderTREND-Vidportal/BuilderTREND-Video-Portal#17]
Issue Handling.  Need to test and handle Vimeo becoming unavailable.  If Vimeo becomes unavailable or has any issues, then we should possibly send an email notification to BuilderTrend.  Also, redirect the user if an issue occurs with Vimeo.

**Comment by Kazzira** [comment]
Finished on Sunday
