### ISSUE TITLE
Improve Upload Video to Vimeo Functionality

### ISSUE THREAD

**Issue by ccpurcell** [Capstone-BuilderTREND-Vidportal/BuilderTREND-Video-Portal#19]
Improve the Upload Video to Vimeo Functionality so that in Vimeo the video has the same Title and Description as it does in the BuilderTrend Video Portal.  Try to also include the video author in Vimeo.  This can help with troubleshooting issues when working with Vimeo, also can help with administrative tasks.

**Comment by DanPatten** [comment]
Completed
