### ISSUE TITLE
Add Delete Video Functionality

### ISSUE THREAD

**Issue by ccpurcell** [Capstone-BuilderTREND-Vidportal/BuilderTREND-Video-Portal#20]
Add Delete Video Functionality.  A Soft Delete.  When delete button clicked in Gridview the video gets removed from the BuilderTrend Video Portal.  However, the video does not got removed from Vimeo Account until a certain amount of time has passed.

**Comment by dswright1990** [comment]
I've started on this. I just made a commit that removes the video from our database but not from vimeo. Still need to find a good icon for the delete button

**Comment by Kazzira** [comment]
Assigning myself to confirmation message dialog before delete

**Comment by Kazzira** [comment]
Confirmation dialog finished.

**Comment by dswright1990** [comment]
Delete button now deletes the video info from our database and from video as requested by the client.

@DanPatten, thanks for the assistance on this task.
