### ISSUE TITLE
Create default thumbnail

### ISSUE THREAD

**Issue by jakemmq** [Capstone-BuilderTREND-Vidportal/BuilderTREND-Video-Portal#26]
Create a default thumbnail to use while waiting for the video.  It should be the BuilderTrend logo with the text "video processing"

**Comment by DanPatten** [comment]
Thumbnail size should be width=200, height=150

**Comment by dswright1990** [comment]
Can we close this issue?

**Comment by DanPatten** [comment]
I added a placeholder image for now - Jake is making the one that says processing

**Comment by jakemmq** [comment]
Here it is.
Jake

**Comment by DanPatten** [comment]
Commit the image to the images folder, its named pending.png
