### ISSUE TITLE
Create Video Popup Page

### ISSUE THREAD

**Issue by DanPatten** [Capstone-BuilderTREND-Vidportal/BuilderTREND-Video-Portal#6]
When a user clicks on a video on the view video page a shadowbox should appear with the video embeded with a Vimeo URL.

**Comment by dswright1990** [comment]
I added a button that opens up a modal that plays a video to the homepage. 
The video url is hardcoded and I haven't messed with the css yet.
Also if you close the modal the video continues to play so the audio is still playing.

**Comment by DanPatten** [comment]
This should be completed.
